# secretlint-disable @secretlint/secretlint-rule-pattern
# temporarily disable until moved to entering environment variables for this
---
services:
  server:
    container_name: tnra
    image: tnra
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tnra
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: mysql
    image: mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 1s
      timeout: 3s
      retries: 30
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tnra
    ports:
      - '3307:3306'
    volumes:
      - 'mysql-db:/var/lib/mysql'
volumes:
  mysql-db:
