-- Flyway baseline migration: captures the existing schema as generated by Hibernate ddl-auto
-- This migration will be skipped on existing databases via flyway.baseline-on-migrate=true

CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255),
    profile_image VARCHAR(255),
    phone_number VARCHAR(255),
    text_email_suffix VARCHAR(255),
    dark_mode BIT,
    active BIT,
    slack_username VARCHAR(255) NOT NULL,
    slack_user_id VARCHAR(255) NOT NULL,
    pq_access_token VARCHAR(4000),
    pq_refresh_token VARCHAR(4000)
);

CREATE TABLE IF NOT EXISTS post (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    start DATETIME(6),
    finish DATETIME(6),
    state TINYINT,
    widwytk TEXT,
    kryptonite TEXT,
    what_and_when TEXT,
    personal_best TEXT,
    personal_worst TEXT,
    family_best TEXT,
    family_worst TEXT,
    work_best TEXT,
    work_worst TEXT,
    exercise INTEGER,
    gtg INTEGER,
    meditate INTEGER,
    meetings INTEGER,
    pray INTEGER,
    _read INTEGER,
    sponsor INTEGER,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_post_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS go_to_guy_set (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    start_date DATETIME(6)
);

CREATE TABLE IF NOT EXISTS go_to_guy_pair (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    caller_id BIGINT,
    callee_id BIGINT,
    go_to_guy_set_id BIGINT NOT NULL,
    CONSTRAINT fk_gtg_pair_caller FOREIGN KEY (caller_id) REFERENCES users(id),
    CONSTRAINT fk_gtg_pair_callee FOREIGN KEY (callee_id) REFERENCES users(id),
    CONSTRAINT fk_gtg_pair_set FOREIGN KEY (go_to_guy_set_id) REFERENCES go_to_guy_set(id)
);
